---
# Atualizacao Red Hat Like
- name: Update System Red Hat Distro
  yum: name=* state=latest security=yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

# Atualizacao Debian Like
- name: Update System Debian Distro
  apt: update_cache=yes upgrade=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
...